/*
***************************************
  USUARIO DE CREACIÓN : JBENITEZ
  DETALLE : MODELO HORIZONTE_MATERIAL_CENTRO_VALIRACION
  FECHA DE CREACIÓN: 18/09/2026
  
  HISTORIAL DE MODIFICACIÓN:		
  --------------------------
  FECHA     |  USUARIO  |  DETALLE  
  ---------------------------------
***************************************
*/

CREATE OR REPLACE TABLE `{horizonte_project_id}.hzt_planeamiento.horizonte_material_centro_valoracion`
(
  des_origen STRING OPTIONS(description="Nombre de tabla origen"),
  val_rownum INT64 OPTIONS (description="Numero de fila "),
  id_material STRING OPTIONS (description="Concateacion para identificar el material"),
  cod_material STRING OPTIONS (description="Codigo_material"),
  cod_stock_material STRING OPTIONS (description="Código de material con stock"),
  des_material STRING OPTIONS (description="Descripcion del material"),
  des_presentacion_material_contendor STRING OPTIONS (description="Descripción del material según el contenedor"),
  flg_materia_prima BOOLEAN OPTIONS (description="Flag de materia prima determina si la descripcion cumple ciertos lineamientos"),
  cod_tipo_material STRING OPTIONS (description="Codigo del tipo de material"),
  cod_tipo_material_fabricacion STRING OPTIONS (description="Tipo de material de la fabricacion"),
  cod_jerarquia STRING OPTIONS (description="Codigo de jerarquia"),
  des_plataforma STRING OPTIONS (description="La plataforma del material "),
  des_subplataforma STRING OPTIONS (description="Subplataforma del material "),
  des_categoria STRING OPTIONS (description="La categoria del material "),
  des_familia STRING OPTIONS (description="La familia del material"),
  des_variedad STRING OPTIONS (description="La variedad"),
  des_presentacion STRING OPTIONS (description="La presentacion"),
  cod_grupo_articulo STRING OPTIONS (description="Codigo grupo de articulo"),
  des_grupo_articulo STRING OPTIONS (description="Descripcion del grupo articulo"),
  est_grupo_articulo_3 STRING OPTIONS (description="Estado del grupo articulo 3"),
  cod_propietario_marca STRING OPTIONS (description="Codigo del dueño de marca"),
  cod_centro STRING OPTIONS (description="Codigo de centro "),
  des_centro STRING OPTIONS (description="Descripción del centro"),
  cod_sociedad STRING OPTIONS (description="Codigo de sociedad"),
  cod_pais STRING OPTIONS (description="Codigo de pais"),
  cod_grupo_transporte STRING OPTIONS (description="Codigo de grupo de transporte"),
  val_tiempo_vida INT64 OPTIONS (description="Tiempo de vida"),
  cod_unidad_base STRING OPTIONS (description="Codigo de unidad base"),
  cod_unidad_almacenamiento STRING OPTIONS (description="Codigo de unidad de almacenamiento"),
  cod_indicador_control_precio STRING OPTIONS (description="Codigo de indicador de control de precio"),
  cod_categoria_valoracion STRING OPTIONS (description="Codigo de categoria"),
  cod_categoria_valoracion_recomendada STRING OPTIONS (description="Codigo de categoria de valoracion recomendada"),
  cod_caracteristica_planificacion STRING OPTIONS (description="Codigo de caracteristica de planificación"),
  flg_caracteristica_planificacion BOOLEAN OPTIONS (description="Flag de la caracteristica de la planificación"),
  cod_clase_aprovisionamiento STRING OPTIONS (description="Codigo de clase de aprovisionamimento"),
  cod_planificacion_necesidad STRING OPTIONS (description="Codigo de planificacion de necesidades"),
  cod_grupo_compra STRING OPTIONS (description="Codigo de grupo de compras"),
  flg_grupo_compra BOOLEAN OPTIONS (description="Flag de grupo de compras"),
  val_tiempo_entrega_previsto INT64 OPTIONS (description="Tiempo de entrega previsto"),
  cod_almacen_aprovisionamiento_externo STRING OPTIONS (description="Codigo de almacen aprovisionamiento"),
  cod_almacen_produccion STRING OPTIONS (description="Codigo de almacen de produccion"),
  cod_grupo_importacion_exportacion STRING OPTIONS (description="Codigo del grupo de importacion exportacion"),
  cod_tipo_aprovisionamiento_especial STRING OPTIONS (description="Codigo de tipo de aprovisionamiento especial"),
  cod_aprovisionamiento_especial STRING OPTIONS (description="Codigo de aprovisionamiento"),
  flg_tiempo_entrega BOOLEAN OPTIONS (description="Flag de tiempo de entrega"),
  des_aprovisionamiento_especial STRING OPTIONS (description="Descripcion del aprovisionamiento especial"),
  cod_centro_origen STRING OPTIONS (description="Codigo del centro de origen"),
  cod_sociedad_origen STRING OPTIONS (description="Codigo de sociedad origen"),
  cod_centro_produccion STRING OPTIONS (description="Código del centro de producción"),
  flg_extendido_centro_origen BOOLEAN OPTIONS (description="Flag de extendido en el centro de origen"),
  cod_grupo_carga STRING OPTIONS (description="Codigo de grupo de carga"),
  cod_grupo_tratamiento_logistico STRING OPTIONS (description="Codigo de tratamiento logistico"),
  cod_grupo_planificacion STRING OPTIONS (description="Codigo de grupo de planificaion"),
  cod_negocio STRING OPTIONS (description="Codigo de negocio"),
  cod_subnegocio STRING OPTIONS (description="Codigo de subnegocio"),
  cod_marca STRING OPTIONS (description="Codigo de marca"),
  cod_grupo_imputacion STRING OPTIONS (description="Codigo de de grupo de imputacion"),
  cod_estado_mantenimiento STRING OPTIONS (description="Codigo de estado de mantenimiento"),
  flg_compra BOOLEAN OPTIONS (description="Flag de compras"),
  flg_venta BOOLEAN OPTIONS (description="Flag de ventas"),
  cod_centro_beneficio STRING OPTIONS (description="Codigo de centro de beneficio"),
  cod_centro_beneficio_propuesto STRING OPTIONS (description="Centro de beneficio propuesto"),
  cod_indicador_impuesto STRING OPTIONS (description="Codigo de indicador de impuestos"),
  val_tiempo_tratamiento_entrada_mercancia INT64 OPTIONS (description="Tiempo de tratamiento de entrada de la mercancia"),
  fec_creacion_material DATE OPTIONS (description="Fecha de creacion del material"),
  des_equipo_creador STRING OPTIONS (description="Nombre del equipo creador del material"),
  cod_usuario_creador STRING OPTIONS (description="Codigo de usuarioo del creador"),
  fec_ultima_modificacion DATE OPTIONS (description="Fecha de la ultima modificacion"),
  cod_usuario_ultima_modificacion STRING OPTIONS (description="Codigo de usuario de la ultima modificacion"),
  cod_determinacion_precio STRING OPTIONS (description="Codigo de deteriminacion del precio"),
  val_determinacion_precio_correcto INT64 OPTIONS (description="Determinacion del precio correcto"),
  cod_indicador_control_precio_2 STRING OPTIONS (description="Indicador de control de precios"),
  cod_indicador_control_precio_correcto STRING OPTIONS (description="Indicador de control de precios correctos"),
  val_precio_actual NUMERIC(18,4) OPTIONS (description="Valor de precio actual"),
  val_cantidad_base INT64 OPTIONS (description="Cantidad base"),
  val_precio_anterior NUMERIC(18,4) OPTIONS (description="Valor del precio anterior"),
  val_variacion_precio NUMERIC(18,4) OPTIONS (description="Variacion del precio"),
  val_ratio_precio_base NUMERIC(18,4) OPTIONS (description="Ratio del precio base"),
  cod_grupo_gasto_general STRING OPTIONS (description="Grupo de gasto general"),
  val_dimension_lote INT64 OPTIONS (description="Tamaño del lote"),
  des_grupo_material_1 STRING OPTIONS (description="Grupo de materiales 1"),
  des_grupo_material_2 STRING OPTIONS (description="Grupo de materiales 2"),
  est_estructura_cuantitativa STRING OPTIONS (description="Estado de estructura cuantitativa"),
  est_material_origen STRING OPTIONS (description="Estado de material origen"),
  cod_tipo_valoracion STRING OPTIONS (description="Codigo de tipo de valoracion"),
  est_costo STRING OPTIONS (description="Estado de no tiene costo"),
  est_material_coproducto STRING OPTIONS (description="Estado del material coproducto"),
  est_libro_material_activo STRING OPTIONS (description="Estado del libro de materiales activo"),
  flg_componente BOOLEAN OPTIONS (description="Flag del componente del material"),
  flg_fert_hawa BOOLEAN OPTIONS (description="Flag de pertenece a ferthawa"),
  est_fert_hawa STRING OPTIONS (description="Status de Fert-Hawa"),
  flg_racionalizacion_caso_uso_3 BOOLEAN OPTIONS (description="Flag de racionalizacion del caso de uso 3 "),
  des_negocio STRING OPTIONS (description="Negocio o GRM1"),
  des_subnegocio STRING OPTIONS (description="Subegocio o GRM2"),
  cod_centro_beneficio_digito_567 STRING OPTIONS (description="Centro de beneficio digitos 567"),
  flg_tipo_mrp BOOLEAN OPTIONS (description="Flag del tipo de mrp"),
  flg_tipo_mrp_2 BOOLEAN OPTIONS (description="Flag del tipo de mrp 2"),
  val_stock_seguridad NUMERIC(18,4) OPTIONS (description="Cantidad de stock de seguridad"),
  val_lote_minimo NUMERIC(18,4) OPTIONS (description="Cantidad de lote minimo"),
  val_numero_redondeo NUMERIC(18,4) OPTIONS (description="Numero de valor de redondeo"),
  est_suspension STRING OPTIONS (description="Estado de suspension"),
  cod_material_reemplazo STRING OPTIONS (description="Codigo de material reemplazo a nivel de la MARA"), 
  cod_material_funcional STRING OPTIONS (description="Código del material a nivel funcional"),
  flg_leadtime BOOLEAN OPTIONS (description="Flag del leadtime"),
  flg_receta BOOLEAN OPTIONS (description="Flag de receta"),
  cod_grupo_receta STRING OPTIONS (description="Codigo de grupo de receta"),
  cod_lista_material STRING OPTIONS (description="Lista de materiales"),
  cod_bloqueo_centro STRING OPTIONS (description="Codigo de bloqueo por centro"),
  flg_grupo_tratamiento_logistico BOOLEAN OPTIONS (description="Flag del grupo de tratamiento logistico"),
  cod_material_reemplazante STRING OPTIONS (description="Codigo de material reemplazante a nivel de centro de la MARC"),
  flg_codigo_material_reemplazante BOOLEAN OPTIONS (description="Flag del código de material reemplazante"),
  flg_centro_ibp BOOLEAN OPTIONS (description="Flag de centros ibp"),
  flg_excepcion_granel BOOLEAN OPTIONS (description="Flag de excepcion de graneles"),
  des_planificacion_necesidad STRING OPTIONS (description="Descripcion de la planificacion de necesidades"),
  flg_aprovisionamiento BOOLEAN OPTIONS (description="Flag de aprovisionamiento"),
  flg_leadtime_mrp BOOLEAN OPTIONS (description="Flag del leadtime de mrp"),
  flg_pedido_automatico BOOLEAN OPTIONS (description="Flag de pedido automático (X)"), 
  est_disponibilidad STRING OPTIONS (description="Estado de disponibilidad del material"), 
  cod_dimension_lote STRING OPTIONS (description="Código de la dimensión del lote"), 
  cod_nuevo_estado_material STRING OPTIONS (description="Código del estado del material para la nueva clasificación Z"), 
  des_tipo_mrp_total STRING OPTIONS (description="Todos los valores del tipo MRP que tiene el material"),
  des_informacion_fabricacion STRING OPTIONS (description="Información de la fabricación (planner)"),
  cod_valor_compra STRING OPTIONS (description="Código de la clave de valor de compra"),
  flg_version_fabricacion BOOLEAN OPTIONS (description="Flag que indica si el material tiene version de fabricacion activa"),
  flg_version_fabricacion_centro BOOLEAN OPTIONS (description="Flag que indica si el material tiene version de fabricacion activa en un centro"),
  flg_version_fabricacion_creado BOOLEAN OPTIONS (description="Flag que indica si el material tiene version de fabricacion activa sin importar el centro"),
  flg_material_maquila BOOLEAN OPTIONS (description="Flag que indica si el material es maquila o no maquila"),
  flg_material_centro_ampliado BOOLEAN OPTIONS (description="Flag que indica si el material está ampliado en su centro correspondiente"),
  flg_material_maquila_completa BOOLEAN OPTIONS (description="Flag que indica si el material es maquila full cost"),
  flg_componente_zhal BOOLEAN OPTIONS (description="Flag que indica si el material ZHAL es componente"),
  flg_componente_zroh_zler BOOLEAN OPTIONS (description="Flag que indica si el material ZROH o ZLER es componente"),
  num_tiempo_duracion INT64 OPTIONS (description="Tiempo de duración"),
  flg_lista_activa BOOLEAN OPTIONS (description="Flag que indica si el material está asociado a una lista de material activa"),
  cnt_stock NUMERIC(18,4) OPTIONS (description="Cantidad de stock del material"),
  mnt_precio_plan NUMERIC(18,4) OPTIONS (description="Monto asociado al plan 1"),
  val_fecha_plan STRING OPTIONS(description="Valor fecha plan 1"),
  fec_inicio_extrema_maxima DATE OPTIONS (description="Fecha de la última producción"),
  des_responsable_material_centro STRING OPTIONS (description="Nombre del responsable del material a nivel centro"),
  des_responsable_material_indirecto STRING OPTIONS (description="Responsable de materiales indirectos"),
  des_responsable_categoria_produccion STRING OPTIONS (description="Nombre del responsable de la categoria en PPROD"),
  des_responsable_clasificacion STRING OPTIONS (description="Nombre del innovation planner, para reglas de Z"),
  des_responsable_distribucion STRING OPTIONS (description="Nombre del responsable de la categoría en PDIS"),
  val_dbkey STRING OPTIONS (description="Identificador único"),
  fec_proceso DATETIME OPTIONS (description="Fecha y hora de ejecución de la tabla")
)
OPTIONS (
  description = 'Tabla de centro de valoración S4'
);