/*
***************************************
  USUARIO DE CREACIÓN : JBENITEZ
  DETALLE : MODELO HORIZONTE_MATERIAL.
  FECHA DE CREACIÓN: 18/09/2026
  
  HISTORIAL DE MODIFICACIÓN:		
  --------------------------
  FECHA     |  USUARIO  |  DETALLE  
  ---------------------------------
***************************************
*/

CREATE OR REPLACE TABLE `{horizonte_project_id}.hzt_planeamiento.horizonte_material`(
  des_origen STRING OPTIONS(description="Nombre de tabla origen"),
  val_rownum INT64                                OPTIONS (description="val_rownum unico del registro"),
  id_material STRING                              OPTIONS (description="Código del material principal que concatena (MAT + DE-WILSON + cod_material))"),
  cod_material STRING                             OPTIONS (description="Código del material"),
  des_material STRING                    OPTIONS (description="Nombre del material"),
  cod_tipo_material STRING                        OPTIONS (description="Código del tipo de material"),
  cod_jerarquia STRING                            OPTIONS (description="Código de la jerarquia del material"),
  cod_plataforma STRING                            OPTIONS (description="Código de la plataforma del material"),
  des_plataforma STRING                            OPTIONS (description="Descripcion de la plataforma del material"),
  cod_subplataforma STRING                            OPTIONS (description="Código de la subplataforma del material"),
  des_subplataforma STRING                            OPTIONS (description="Descripcion de la subplataforma del material"),
  cod_categoria STRING                                OPTIONS (description="Codigo de la categoría del material"),
  des_categoria STRING                                OPTIONS (description="Descripción de la categoría del material"),
  cod_familia STRING                              OPTIONS (description="Código de la familia del material"),
  des_familia STRING                                  OPTIONS (description="Descripción de la familia del material"),
  cod_variedad STRING                                 OPTIONS (description="Código de la variedad del material"),
  des_variedad STRING                                 OPTIONS (description="Descripcion de la variedad del material"),
  cod_presentacion STRING                             OPTIONS (description="Código de la presentacion del material"),
  des_presentacion STRING                             OPTIONS (description="Descripcion de la presentacion del material"),
  cod_categoria_producto STRING                       OPTIONS (description="Código de la categoría del material"),
  flg_excepcion_material BOOLEAN                     OPTIONS (description="Flag de exclusion exclusivo para reglas de fletes de planeamiento de la distribucion"),
  num_longitud_codigo_jerarquia INT64                          OPTIONS (description="Cantidad de carácteres de la jerarquia del material"),
  num_longitud_correcta_jerarquia INT64                 OPTIONS (description="Cantidad correcta de carácteres de la jerarquia del material"),
  flg_materia_prima BOOLEAN                          OPTIONS (description="Flag que indica si el material es materia prima"),
  flg_dummy BOOLEAN                                  OPTIONS (description="Flag que indica si el material es dummy"),
  cod_material_interfaz STRING                    OPTIONS (description="Código del material funcional"),
  est_longitud_material STRING                      OPTIONS (description="Flag que hace referencia a la cantidad de caracteres del código de material"),
  cod_grupo_articulo STRING                       OPTIONS (description="Código del grupo del artículo"),
  des_grupo_articulo STRING                       OPTIONS (description="Descripción del grupo del artículo"),
  flg_grupo_articulo BOOLEAN                         OPTIONS (description="Flag de grupo de artículo"),
  cod_grupo_articulo_propuesto STRING                 OPTIONS (description="Código del grupo del artículo propuesto"),
  cod_grupo_articulo_2 STRING                         OPTIONS (description="Código del grupo del artículo 2"),
  cod_grupo_articulo_3 STRING                         OPTIONS (description="Código del grupo del artículo 3"),
  cod_sociedad STRING                             OPTIONS (description="Código de sociedad"),
  flg_centro BOOLEAN                                 OPTIONS (description="Flag si contiene centro"),
  flg_organizacion_venta BOOLEAN                     OPTIONS (description="Flag si contiene organización de venta"),
  cod_unidad_base STRING                          OPTIONS (description="Código de unidad base"),
  cod_bloqueo STRING                              OPTIONS (description="Código de bloqueo a nivel de material"),
  cod_grupo_transporte STRING                     OPTIONS (description="Código de grupo de transporte"),
  des_grupo_transporte STRING                         OPTIONS (description="Descripción de grupo de transporte"),
  num_tiempo_vida INT64                                 OPTIONS (description="Tiempo de vida"),
  num_tiempo_duracion INT64                             OPTIONS (description="Tiempo de duración"),
  cod_unidad_tiempo_vida STRING                       OPTIONS (description="Código unidad de medida de tiempo de vida"),
  est_actualizacion STRING                     OPTIONS (description="Estado de la actualización"),
  est_actualizacion_completa STRING            OPTIONS (description="Estado de la actualización completa"),
  cod_duenio_marca STRING                         OPTIONS (description="Código del dueño de la marca"),
  des_duenio_marca STRING                               OPTIONS (description="Nombre del fabricante"),
  cod_onu_cubso STRING                            OPTIONS (description="Código onu cubso"),
  cod_unidad_tiempo STRING                        OPTIONS (description="Código de unidad de medida de tiempo"),
  num_peso_bruto_unidad_base NUMERIC(20,4)            OPTIONS (description="Peso bruto unidad base"),
  num_peso_neto_unidad_base NUMERIC(20,4)             OPTIONS (description="Peso neto unidad base"),
  cod_unidad_peso_base STRING                     OPTIONS (description="Código de unidad de medida de peso"),
  num_peso_bruto_kg NUMERIC(20,4)                     OPTIONS (description="Peso bruto en kilos"),
  num_peso_neto_kg NUMERIC(20,4)                      OPTIONS (description="Peso neto en kilos"),
  flg_conversion_kg BOOLEAN                          OPTIONS (description="Flag para convertir a kilos"),
  num_numerador_kg INT64                                OPTIONS (description="Numerador de conversión a kilos"),
  num_denominador_kg INT64                              OPTIONS (description="Denominador de conversión a kilos"),
  num_peso_convertido_kg NUMERIC(20,4)                OPTIONS (description="Peso convertido a kilos"),
  flg_unidad_comercial BOOLEAN                       OPTIONS (description="Flag de unidad comercial"),
  cod_unidad_comercial_material STRING                OPTIONS (description="Código de unidad de medida comercial"),
  num_peso_bruto_unidad_comercial NUMERIC(20,4)       OPTIONS (description="Peso bruto unidad comercial"),
  cod_unidad_peso_comercial STRING                    OPTIONS (description="Código de unidad de medida peso comercial"),
  num_peso_unidad_comercial_kg NUMERIC(20,4)          OPTIONS (description="Peso comercial en kilos"),
  num_numerador_conversion_uco INT64                    OPTIONS (description="Numerador de conversión a UCO"),
  num_denominador_conversion_uco INT64                  OPTIONS (description="Denominador de conversión a UCO"),
  num_peso_bruto_unidad_base_calculado NUMERIC(20,4)  OPTIONS (description="Peso bruto unidad base calculado"),
  num_variacion_peso_uco_unidad_base NUMERIC(20,4)    OPTIONS (description="Variación de peso uco con unidad base"),
  cod_planner STRING                              OPTIONS (description="Código de planner"),
  flg_sujeto_a_lote BOOLEAN                        OPTIONS (description="Flag que indica lote"),
  fec_creacion_material DATE                      OPTIONS (description="Fecha de creación"),
  des_equipo_creador STRING                       OPTIONS (description= "Descripcion del equipo creador"),
  cod_usuario_creador STRING                      OPTIONS (description="Código del usuario creador"),
  fec_ultima_modificacion DATE                    OPTIONS (description="Fecha de última modificación"),
  cod_usuario_ultima_modificacion STRING          OPTIONS (description="Código del usuario de modificación"),
  flg_alicorp BOOLEAN                                OPTIONS (description="Flag Alicorp"),
  flg_alicorp_intradevco BOOLEAN                             OPTIONS (description="Flag Intradevco"),
  num_tiempo_vida_anterior INT64                        OPTIONS (description="Tiempo de vida anterior"),
  cod_unidad_tiempo_vida_anterior STRING                   OPTIONS (description="Código de unidad de medida del tiempo anterior"),
  fec_tiempo_vida_anterior DATE                      OPTIONS (description="Fecha de tiempo de vida anterior"),
  flg_tiempo_vida BOOLEAN                            OPTIONS (description="Flag de tiempo de vida"),
  cod_bloqueo_venta STRING                        OPTIONS (description="Código de bloqueo de la venta"),
  cod_negocio STRING                              OPTIONS (description="Código de negocio"),
  des_grupo_material1 STRING                        OPTIONS (description="Descripcion de grupo de materiales 1"),
  cod_subnegocio STRING                           OPTIONS (description="Código de subnegocio"),
  des_grupo_material2 STRING                        OPTIONS (description="Descripcion de grupo de materiales 2"),
  cod_marca STRING                                OPTIONS (description="Código de marca"),
  des_grupo_material4 STRING                        OPTIONS (description="Descripcion de grupo de materiales 4"),
  cod_unidad_almacenamiento STRING                    OPTIONS (description="Código de unidad almacenamiento"),
  num_numerador_conversion_unidad_almacenamiento INT64        OPTIONS (description="Numerador de conversión almacenamiento"),
  num_denominador_conversion_unidad_almacenamiento INT64      OPTIONS (description="Denominador de conversión almacenamiento"),
  num_peso_bruto_almacenamiento NUMERIC(20,4)         OPTIONS (description="Peso bruto almacenamiento"),
  num_peso_neto_almacenamiento NUMERIC(20,4)          OPTIONS (description="Peso neto almacenamiento"),
  num_numerador_conversion_paleta INT64                 OPTIONS (description="Numerador de conversión paleta"),
  num_denominador_conversion_paleta INT64               OPTIONS (description="Denominador de conversión paleta"),
  num_peso_neto_paleta NUMERIC(20,4)                  OPTIONS (description="Peso neto paleta"),
  num_volumen_unidad_base NUMERIC(22,4)               OPTIONS (description="Volumen base"),
  cod_unidad_volumen_base STRING                      OPTIONS (description="Código de unidad de medida volumen"),
  flg_fert_hawa BOOLEAN                               OPTIONS (description="Flag pertenece a fert-hawa"),
  cod_estado STRING                                   OPTIONS (description="Codigo de estado"), 
  cod_estado_nuevo STRING                             OPTIONS (description="Codigo de estado nuevo"), 
  flg_raciolizacion_cu03 BOOLEAN                      OPTIONS (description="Flag pertenece a racionalización"),
  cod_material_reemplazo STRING                       OPTIONS (description="Código de material de reemplazo"),
  cod_material_reemplazo_recursivo STRING             OPTIONS (description="Código de material de reemplazo del material reemplazante"),
  flg_stock BOOLEAN                                   OPTIONS (description="Flag stock"),
  flg_lista_material BOOLEAN                                     OPTIONS (description="Flag pertenece a lista de materiales"),
  cod_centro_concatenado_lista_material STRING         OPTIONS (description="Centros de lista de materiales"),
  flg_intradevco BOOLEAN                                OPTIONS (description="Flag pertenece a INTRADEVCO"),
  flg_excepcion_granel BOOLEAN                          OPTIONS (description="Flag de excepcion para la denominación del material"),
  flg_zhal BOOLEAN                                    OPTIONS (description="Flag para indentificar los codigos de material que comienzan con H"),
  cod_grupo_tipo_posicion_general STRING          OPTIONS (description="Codigo del grupo de tipo de posicion general"),
  cod_ramo STRING                                   OPTIONS (description="Codigo de ramo"),
  flg_grupo_articulo_2 BOOLEAN                                OPTIONS (description="Flag de grupo de articulo"),
  flg_peso_bruto BOOLEAN                                OPTIONS (description="Flag de peso bruto"),
  flg_exclusion_categoria_valorizacion BOOLEAN OPTIONS(description="Flag de materiales excluidos por categoria valorizacion"),
  flg_mrp_activo BOOLEAN OPTIONS (description="Flag que indica si el material está activo en algún centro a nivel MRP"),
  cod_condicion_almacenaje STRING OPTIONS (description = "Código de la condición de almacenamiento"),
  cnt_stock NUMERIC(18,4) OPTIONS (description="Cantidad de stock del material"),
  est_clase_001 STRING OPTIONS (description="Indica si el material tiene clase 001"),
  est_clase_023 STRING OPTIONS (description="Indica si el material tiene clase 023"),
  flg_clase_material BOOLEAN options (description="Indica si el material tiene clase 001 y 023"),
  des_responsable_material STRING OPTIONS (description="Nombre del responsable del material"),
  des_responsable_material_indirecto STRING OPTIONS (description="Responsable de materiales indirectos"),
  fec_movimiento_consumo_201_261 DATE                      OPTIONS (description="Fecha de ultimo consumo 201 o 206"),
  fec_movimiento_consumo_101 DATE                      OPTIONS (description="Fecha ultimo consumo 101"),
  fec_fin_validez_contrato DATE                      OPTIONS (description="Fecha de ultimo contrato"),
  cod_bloqueo_comercial STRING  OPTIONS (description="Indica si el material tiene bloqueo comercial"),
  des_responsable_distribucion STRING OPTIONS (description="Nombre del responsable de la categoría en PDIS"),
  val_dbkey STRING OPTIONS (description="Identificador único"),
  fec_proceso DATETIME OPTIONS (description="Fecha de ejecucion del proceso")
)
OPTIONS (
    description = 'Tabla usada para la calidad de datos de los materiales base'
);